blank_issues_enabled: false
contact_links:
  - name: Discord
    url: https://discord.gg/zEwGEJUPRC
    about: If you need quick support or have qustions, the discord ist perfect
  - name: Wiki
    url: https://github.com/New-Time-Development/OmeCord/wiki
    about: You can find answers to common questions on our Wiki.
  - name: Docs
    url: https://github.com/New-Time-Development/OmeCord/tree/docs
    about: You can find our docs. You can read something about the code
